version: "3.9"

services:
  labelmaster-1-0-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labelmaster-1-0-el-arbol
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_PORT: "8501"
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
    volumes:
      # Persistir base SQLite entre reinicios del contenedor
      - ./catalogo.db:/app/catalogo.db
